[tool.poetry]
name = "test"
version = "0.0.1"
description = ""
authors = [""]

[tool.poetry.dependencies]
python = ">=3.9,<3.10"
numpy="2.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"