[tool.poetry]
name = "test"
version = "0.0.1"
description = ""
authors = [""]

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
numpy="2.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"